CREATE DATABASE [J3.L.P0017_Photographer]
GO 
USE [J3.L.P0017_Photographer]
GO

/*CREATE TABLE*/
CREATE TABLE [GALLERY](
[ID] INT  IDENTITY(1,1) PRIMARY KEY,
[TITLE] VARCHAR(255),
[DESCRIPTION] TEXT,
[THUMNAIL] VARCHAR(255)
)

CREATE TABLE [PHOTO](
[ID] INT  IDENTITY(1,1) PRIMARY KEY,
[IMAGE] VARCHAR(255),
[DESCRIPTION] TEXT,
[GALLERYID] INT FOREIGN KEY REFERENCES dbo.GALLERY(ID)
)

CREATE TABLE [CONTACT](
[ID] INT  IDENTITY(1,1) PRIMARY KEY,
[PHOTOGRAPHER] VARCHAR(255),
[ADDRESS] VARCHAR(255),
[CITY] VARCHAR(255),
[COUNTRY] VARCHAR(255),
[TEL] VARCHAR(16),
[EMAIL] VARCHAR(255)
)

CREATE TABLE [COUNTER](
[ID] INT  IDENTITY(1,1) PRIMARY KEY,
[PAGECOUNTER] INT
)

