DROP DATABASE[J3.L.P0023_Electronics_Online_Store]
GO
CREATE DATABASE [J3.L.P0023_Electronics_Online_Store]
GO
USE [J3.L.P0023_Electronics_Online_Store]
GO

/*CREATE TABLE*/
CREATE TABLE [PRODUCT](
[ID] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
[NAME] VARCHAR(255),
[IMAGE] VARCHAR(255),
[DESCRIPTION] TEXT,
[PRICE] FLOAT,
[QUANTITY] INT
)

CREATE TABLE [CUSTOMER](
[ID] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
[NAME] VARCHAR(255),
[COMPANY] VARCHAR(255),
[ADDRESS1] VARCHAR(255),
[ADDRESS2] VARCHAR(255),
[ZIP] VARCHAR(255),
[CITY] VARCHAR(255),
[STATE] VARCHAR(255),
[COUNTRY] VARCHAR(255),
[PHONE] VARCHAR(255),
[EMAIL] VARCHAR(255),
[COMMENT] VARCHAR(255),
)


CREATE TABLE [ORDER](
[ID] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
[CUSTOMERID] INT FOREIGN KEY REFERENCES dbo.CUSTOMER(ID),
[DATE] DATE
)

CREATE TABLE [ORDER_PRODUCT](
[ID] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
[QUANTITY] INT ,
[ORDERID] INT FOREIGN KEY REFERENCES dbo.[ORDER](ID),
[PRODUCTID] INT FOREIGN KEY REFERENCES dbo.PRODUCT(ID)
)

CREATE TABLE [MESSAGE](
[ID] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
[NAME] VARCHAR(255),
[EMAIL] VARCHAR(255),
[CONTENT] TEXT
)
/*CREATE TABLE*/
/*INSERT*/
INSERT INTO dbo.PRODUCT
(NAME,IMAGE,DESCRIPTION,PRICE,QUANTITY)
VALUES
('Television', 'i285978589337227269._rsw480h360_szw480h360_.jpg','Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod.',
260, 100);
INSERT INTO dbo.PRODUCT
(NAME,IMAGE,DESCRIPTION,PRICE,QUANTITY)
VALUES
('GPS', 'i285978589337227261._rsw480h360_szw480h360_.jpg','Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod.',
180, 100);
INSERT INTO dbo.PRODUCT
(NAME,IMAGE,DESCRIPTION,PRICE,QUANTITY)
VALUES
('Headphones', 'i285978589337227255._rsw480h360_szw480h360_.jpg','Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod.',
220, 100);
INSERT INTO dbo.PRODUCT
(NAME,IMAGE,DESCRIPTION,PRICE,QUANTITY)
VALUES
('NoteBook', 'i285978589337769103._rsw480h480_szw480h480_.jpg','Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod.',
260, 100);
INSERT INTO dbo.PRODUCT
(NAME,IMAGE,DESCRIPTION,PRICE,QUANTITY)
VALUES
('Smartphone charger', 'i285978589337769145._rsw480h480_szw480h480_.jpg','Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod.',
160, 100);
INSERT INTO dbo.PRODUCT
(NAME,IMAGE,DESCRIPTION,PRICE,QUANTITY)
VALUES
('Router', 'i285978589337227283._rsw480h360_szw480h360_.jpg','Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod.',
320, 100);

/*INSERT*/
/**/

/*QUERY*/
SELECT * FROM dbo.PRODUCT WHERE ID=1

SELECT * FROM dbo.CUSTOMER

SELECT TOP(6) * FROM dbo.PRODUCT


/*Checkout*/
INSERT INTO dbo.CUSTOMER
VALUES
('TASS', 'FPT','HL','','1000','HN','xxx','VN','0199999999','tasszz2k@gmail.com','gut gut!')

INSERT INTO dbo.[ORDER]
VALUES
(1, GETDATE())

INSERT INTO dbo.ORDER_PRODUCT
(QUANTITY,ORDERID,PRODUCTID)
VALUES
(1,1,1)

UPDATE dbo.PRODUCT
SET QUANTITY = 99
WHERE ID = 1
/*Checkout*/

SELECT * FROM dbo.[ORDER]
SELECT * FROM dbo.[PRODUCT]
SELECT * FROM dbo.ORDER_PRODUCT

INSERT INTO dbo.MESSAGE
(NAME,EMAIL,CONTENT)
VALUES
('TASS', 'tass@gmail.com','hello')

SELECT * FROM dbo.MESSAGE