DROP DATABASE[J3.L.P0023_Electronics_Online_Store]
GO
CREATE DATABASE [J3.L.P0023_Electronics_Online_Store]
GO
USE [J3.L.P0023_Electronics_Online_Store]
GO

/*CREATE TABLE*/
CREATE TABLE [PRODUCT](
[ID] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
[NAME] VARCHAR(255),
[DESCRIPTION] TEXT,
[PRICE] FLOAT,
[QUANTITY] INT
)

CREATE TABLE [CUSTOMER](
[ID] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
[NAME] VARCHAR(255),
[COMPANY] VARCHAR(255),
[ADDRESS1] VARCHAR(255),
[ADDRESS2] VARCHAR(255),
[ZIP] VARCHAR(255),
[CITY] VARCHAR(255),
[STATE] VARCHAR(255),
[COUNTRY] VARCHAR(255),
[PHONE] VARCHAR(255),
[EMAIL] VARCHAR(255),
[COMMENT] VARCHAR(255),
)


CREATE TABLE [ORDER](
[ID] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
[CUSTOMERID] INT FOREIGN KEY REFERENCES dbo.CUSTOMER(ID),
[DATE] DATE
)

CREATE TABLE [ORDER_PRODUCT](
[ID] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
[QUANTITY] INT ,
[ORDERID] INT FOREIGN KEY REFERENCES dbo.[ORDER](ID),
[PRODUCTID] INT FOREIGN KEY REFERENCES dbo.PRODUCT(ID)
)

CREATE TABLE [MESSAGE](
[ID] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
[NAME] VARCHAR(255),
[EMAIL] VARCHAR(255),
[CONTENT] TEXT
)
/*CREATE TABLE*/


/*QUERY*/
DROP TABLE dbo.[ORDER]
DROP TABLE dbo.CUSTOMER
DROP TABLE dbo.PRODUCT
DROP TABLE dbo.STOCK
DROP TABLE dbo.ORDER_PRODUCT

SELECT * FROM dbo.CUSTOMER